# Set root logger to INFO or DEBUG to see detailed output from any dependency
rootLogger=WARN, stdout, file
appender.stdout.type=Console
appender.stdout.name=stdout
appender.file.type=RollingFile
appender.file.name=file
appender.file.fileName=log/oersi-etl.log
appender.file.filePattern=log/oersi-etl.log.%i
appender.file.policy.type=SizeBasedTriggeringPolicy
appender.file.policy.size=10MB

# Set loggers to DEBUG or TRACE to see detailed output from the ETL processes
logger.metafacture.name=org.metafacture.json
logger.metafacture.level=INFO
logger.oersi.name=oersi
logger.oersi.level=INFO

# The format of log messages:
appender.stdout.layout.type=PatternLayout
appender.stdout.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%p] [%c{1}:%L] %m%n
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%p] [%c{1}:%L] %m%n