/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indexer;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class IndexerTest {
    @Test
    public void testSomeLibraryMethod() {
        Indexer classUnderTest = new Indexer();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
